### PR TITLE
ci(github): add labeler config to automatically label pull-requests

### PR DESCRIPTION
**Pull request by danibix95**
## Goal

Automatically add labels to PRs, so that reviewers have an easier time in navigating the ones they should be interested in.

## Description

This PR introduce a configuration that trigger a Github feature for automatically adding labels on PRs, depending on which files have been modified within the PR.

The feature is describe here: https://github.com/actions/labeler

## Pull Request Type

- [ ] Documentation content changes
- [ ] Bugfix / Missing Redirects
- [X] Docusaurus site code changes

## PR Checklist

- [X] The commit message follows our guidelines included in the [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md#how-to-submit-a-pr)
- [ ] All tests of Lint, cspell and check-content pass. ([How to launch them?](../blob/main/CONTRIBUTING.md#content-checks))
- [X] No sensitive content has been committed

### CODE REVIEW

**Comment by fredmaggiowski** [comment]
nice, did you check all the labels are correct? You configured all of them using kebab-case but we also have labels with a human readable text (I think we should converge on a single format also @akelity what do you think?)

**Comment by akelity** [comment]
> Nice!!
> 
> Did you check all the labels are correct? You configured all of them using kebab-case but we also have labels with a human readable text (I think we should converge on a single format also @akelity what do you think?)

Yes, it's better to choose a unique format. Perhaps for the simplicity of the action, I would leave this as a label (kebab-case) and modify the ones readable by humans.

**Review by akelity — APPROVED** [review]
LGTM

**Comment by danibix95** [comment]
Should I proceed with renaming labels into kebab-case?

Also, currently I inserted only the main labels regarding the products. If finer classification is needed, feel free to update the list with the correct documentation path.

**Comment by fredmaggiowski** [comment]
> Should I proceed with renaming labels into kebab-case?

I think @akelity is fine with the current naming

> Also, currently I inserted only the main labels regarding the products. If finer classification is needed, feel free to update the list with the correct documentation path.

We can add more later once we have it running :)

**Pull request merged**
