### PR TITLE
feat: udpated screenshots showing Enhanced Workflow icon

### PR DESCRIPTION
**Pull request by ThisIsDemetrio**
## Description

Updated screenshot for the "Migrate to Enhanced Workflow" using a new icon.

Updated screenshots related to the "Revisions" page and "Versions" page showing the "New look and feel" navigation and the Enhanced Workflow icon activated.

## Pull Request Type

- [X] Documentation content changes
- [ ] Bugfix / Missing Redirects
- [ ] Docusaurus site code changes

## PR Checklist

- [X] The commit message follows our guidelines included in the [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md#how-to-submit-a-pr)
- [X] All tests of Lint, cspell and check-content pass. ([How to launch them?](../blob/main/CONTRIBUTING.md#content-checks))
- [X] No sensitive content has been committed

### CODE REVIEW

**Comment by GiovannaMonti** [comment]
I don't know if it's a problem that we see the disabled delete buttons in the revision / version overview screenshots

**Review by GiovannaMonti — APPROVED** [review]

**Review by fredmaggiowski — APPROVED** [review]
LGTM

**Comment by fredmaggiowski** [comment]
This should be merged after v12.3.0 release

**Review by MIA-Deltat1995 — APPROVED** [review]

**Review by GiovannaMonti — APPROVED** [review]

**Comment by danibix95** [comment]
@ThisIsDemetrio would it be possible to align the PR, so that it can be merged?

**Pull request merged**
