### PR TITLE
chore(marketplace): update mongodb compatibility matrix on fast-data

### PR DESCRIPTION
**Pull request by amountainram**
## Description

Update the `compatibility matrix` page for MongoDB on the `marketplace` section

## Pull Request Type

- [x] Documentation content changes

## PR Checklist

- [x] The commit message follows our guidelines included in the [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md#how-to-submit-a-pr)
- [x] All tests of Lint, cspell and check-content pass. ([How to launch them?](../blob/main/CONTRIBUTING.md#content-checks))

### CODE REVIEW

**Comment by TheRusCompass** [comment]
@amountainram @danibix95 mancano le righe sulle ultime versioni del RTU, SVC e sarebbe da aggiungere PS e SVTG

**Comment by amountainram** [comment]
> @amountainram @danibix95 mancano le righe sulle ultime versioni del RTU

Screenshot from 2024-01-25 13-59-38

quali?

**Comment by amountainram** [comment]
@TheRusCompass added v6 and v7 for `Real-Time Update`

**Review by TheRusCompass — APPROVED** [review]
lgtm

**Pull request merged**
